baseURL = "/"
languageCode = "en-us"
title = "PWN 2 FUN"
theme = "anubis2"

publishDir = "public"
canonifyURLs = true

copyright = "© 000pp"

pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

toc = true
locale = "pt-br"

readNextPosts = 2

paginationSinglePost = true

enableEmoji = true
enableRobotsTXT = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[pagination]
pagerSize = 5

[params.author]
name = "000pp"

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 2

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 3

[[menu.main]]
name = "Archive"
identifier = "archive"
url = "/posts/"
weight = 4

[markup.goldmark.renderer]
unsafe = true # Enable unsafe mode to have a better experience

[markup.highlight]
style = 'catppuccin-frappe' # Find more style at here: https://swapoff.org/chroma/playground/
tabWidth = 4

[params.anubis2]
enableCopyCodeButton = true
colorTheme = "auto"
enableColorThemeSwitcher = true
hideFooterAttribution = true
enableReadMoreButton = true